### ISSUE TITLE
Hello, may I ask the results of the search how the dictionary nested the dictionary, at the time of the query

### ISSUE THREAD

**Issue by zhangjianjun056** [stephencelis/SQLite.swift#935] opened 2019-06-04 00:45 UTC
Hello, may I ask the results of the search how the dictionary nested the dictionary, at the time of the query.

Now：
{
  "age": 18,
  "personId":1,
  "name": "zhangsan",
  "height": 180,
  "weight": "60",
  "d_name": "wangcai",
  "d_age": 2
}

Expectation：
{
  "age": 18,
  "personId":1,
  "name": "zhangsan",
  "height": 180,
  "weight": "60",
  "dog": {
    "d_name": "wangcai",
    "d_age": 2
  }
}

**Comment by NathanFallet** [comment] 2021-08-23 22:27
Duplicate of #998

**Closed** 2021-08-23 22:27 UTC
