### ISSUE TITLE
syntax error when using != and >= and <= in Xcode 10.2

### ISSUE THREAD

**Issue by arjavlad** [stephencelis/SQLite.swift#892] opened 2019-03-26 13:20 UTC
var query = getTable().filter(expressionStatus != 81).filter(expressionDueDate <= today || expressionStartDate <= today)

query.asSQL() gives me this query. 
SELECT * FROM "AIRISDLTask" WHERE (("status" !=(_:_:) 81) AND (("dueDate" <=(_:_:) '2019-03-26T12:31:38.356') OR ("startDate" <=(_:_:) '2019-03-26T12:31:38.356')))

When this query is executed it returns error:

[logging] near ":_": syntax error

I'm using latest pods and Xcode 10.2

**Comment by tanzolone** [comment] 2019-03-26 14:11
Duplicate of #888

**Closed** 2019-03-26 16:46 UTC
