### ISSUE TITLE
How to write tests ?

### ISSUE THREAD

**Issue by kmuddapu** [stephencelis/SQLite.swift#655] opened 2017-05-19 12:26 UTC
Thanks for the library,
When I run the tests in example it initialized InMemoryConnection. 

How to write the tests for my DB classes.  Need to use temporaryConnection for tests and InMemoryConnection for production ?

**Comment by bpo217** [comment] 2018-03-14 06:04
Alright.  There's a lot of contextual information that you aren't providing.  Maybe this answer will narrow things down to the answer you're looking for.  

```
import SQLite
import XCTest

class MyTests: XCTestCase {

  //MARK: Overrides
  
  override func setup() {
    super.setup()
    connection = try? Connection()
    XCTAssertNotNil(connection)
  }

  override func teardown() {
    connection = nil
    super.teardown()
  }

  //MARK: Properties

  var connection: Connection!

  //MARK: Tests

  //Each test will have its own "temporary connection."
  //This connection and the database behind it will be wiped after every test.
  //Indeed, an "InMemoryConnection" is a temporary connection in this context.
  //Plus, you really should use an "InMemoryConnection" for tests anyway.

  func test_number1() {
    //Use your database connection in here!
  }

  func test_number2() {
    //Use your database connection in here!
  }
}
```

**Comment by jberkel** [comment] 2021-08-24 13:27
not a bug report, closing.

**Closed by jberkel** 2021-08-24 13:27 UTC
Labels: question
