### ISSUE TITLE
Number without dot become nil

### ISSUE THREAD

**Issue by Chiliec** [stephencelis/SQLite.swift#370] opened 2016-03-14 13:48 UTC
We have existing database with rows, which contains:
- real numbers, with numbers after dots, for example "321.321321"
- numbers without dots, for example "123"
- null

When we try to parse it with `Expression<Double?>`, number without dot become nil. What do you recommend for us?

**Comment by groue** [comment] 2016-03-15 08:45
Hello @Chiliec. It looks like a duplicate of https://github.com/stephencelis/SQLite.swift/issues/331.

**Comment by Chiliec** [comment] 2016-03-22 10:01
#371 resolves my problem.

**Comment by jberkel** [comment] 2016-12-07 16:38
closing as dup (#331)

**Closed by jberkel** 2016-12-07 16:38 UTC
