### ISSUE TITLE
Database version

### ISSUE THREAD

**Issue by 4bottiglie** [stephencelis/SQLite.swift#490] opened 2016-09-06 20:55 UTC
Hi, good job with this lib, very easy to understand and use.
I'm coming from an Android, there i was using the `SQLiteOpenHelper` class, that was handling the **opening** of the database and **upgrade** it if was an older _version_ with a method `void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion)`  . The class `SQLiteDatabase` has a useful method `getVersion()`  that essentially calls  : `"PRAGMA user_version"`  to get it's version. I suggest to add a similar behavior while opening the database to support and understand how to upgrade a older database to the new one.

Update questions:
Is there any way to get the `[Binding?]` from a `Row` , or iterate a Statement with `Row` ? like
`for row in statement{}`
where _row_ is a `Row` type?

**Comment by 4bottiglie** [comment] 2016-09-07 00:56
Something like:
Extension:  http://pastebin.com/Wfz22uTa

SQLiteOpenHelper: http://pastebin.com/iuJ8nnab

And you could use SQLiteOpenHelper to get the connection

**Comment by MrMage** [comment] 2016-09-14 08:48
Have a look at https://github.com/garriguv/SQLiteMigrationManager.swift, that worked well for me.

**Comment by jberkel** [comment] 2016-12-07 16:15
Not a bug, closing.

**Closed by jberkel** 2016-12-07 16:15 UTC
