### ISSUE TITLE
App crash in Xcode 10.2 & error: unrecognized token: ":"

### ISSUE THREAD

**Issue by milan-galitein** [stephencelis/SQLite.swift#894] opened 2019-03-28 07:01 UTC
App crash for this line: try! db.scalar(table.count)

Error:  unrecognized token: ":"

**Comment by tanzolone** [comment] 2019-03-28 09:57
Duplicate of #888

**Closed** 2019-03-29 05:10 UTC

**Comment by eschao** [comment] 2019-03-31 10:09
@tanzolone & @milan-galitein Is it really solved? I updated the latest with carthage and built again, but still have the same problem in my app:
```
2019-03-31 18:08:15.747002+0800 [4122:899969] [logging] unrecognized token: ":"
```

**Comment by vajjhalas** [comment] 2019-04-03 11:49
as per https://github.com/stephencelis/SQLite.swift/issues/895

"it still does't work (Cocoapods),
but "pod 'SQLite.swift', :git => 'https://github.com/stephencelis/SQLite.swift', :branch => 'master'
" is working right."

**Comment by juanjoseluisgarcia** [comment] 2019-04-06 10:37
it doesn't work  on carthage either.

**Comment by mitesh-iosdev** [comment] 2019-04-07 12:31
Yes, I am facing the same issue :(. Anyone got solution for this?
[2901:106131] [logging] unrecognized token: ":"

**Comment by juanjoseluisgarcia** [comment] 2019-04-07 14:30
@mitesh-iosdev my fix is to move to GRDB.swift. It works with Swift 5. It gives warnings but works well except for the in memory database that I don’t use.

**Comment by joris1995** [comment] 2019-04-16 08:53
Is there any fix for this issue yet? I have a swift 5 project had to force my pods to swift 4.2 for SQLite.swift to compile but I am still getting an error when doing a `database.scalar(anything)`: `unrecognized token: ":" (code: 1)`. I Tried @vajjhalas' fix but that doesn't work for me either.

**Comment by juanjoseluisgarcia** [comment] 2019-04-16 09:10
It seems the author is busy and has abandoned the project. There is no even a help wanted sign on the issue so we can submit a pull request... As I said I already switched to GRDB.swift

**Comment by ulaserdegor** [comment] 2019-04-16 12:05
I'm having the same problem. Estimated when it is solved?

**Comment by Samback** [comment] 2019-04-16 12:07
Hi to all,
I have faced yesterday with the same issue. Check your query request, I had a problem with  ` != ""`

**Comment by mitesh-iosdev** [comment] 2019-04-17 03:02
I resolved the issue by master branch and working for me. Please try once

> **pod 'SQLite.swift', :git => 'https://github.com/stephencelis/SQLite.swift', :branch => 'master'**
