### ISSUE TITLE
Force Cast Violation alert  as you are using try! without catch. Can you correct it.

### ISSUE THREAD

**Issue by shraddhachoubey** [stephencelis/SQLite.swift#1020] opened 2020-08-17 11:25 UTC
public var userVersion: Int32 {
        get { return Int32(try! scalar("PRAGMA user_version") as! Int64)}
        set { try! run("PRAGMA user_version = \(newValue)") }
    }

**Comment by NathanFallet** [comment] 2021-08-21 16:45
Duplicate of #1054

**Closed by NathanFallet** 2021-08-21 16:45 UTC
Labels: duplicate
