### ISSUE TITLE
Create table from Codable

### ISSUE THREAD

**Issue by kwstasna** [stephencelis/SQLite.swift#879] opened 2019-02-04 19:43 UTC
Is there any way to create a table from a model which conforms to codable?
For example

class User: Codable {
  let pk: Int?
  etc.. 
}

**Comment by anilsutariya** [comment] 2019-03-22 09:35
Below Like that.
struct Person:Codable {
    
    let personID:Int
    let personName:String?
    let type:String?
   
    
    init(personID:Int:Int,personName:String,type:String) {
        
        self. personID = personID
        self. personName = personName
        self.type = type
  
    }
    
    enum CodingKeys:String,CodingKey {
        
        case personName
        case personID
   
    }
}

**Comment by codingspark** [comment] 2019-04-10 05:51
You have to create the table manually:
https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#creating-a-table

Check previous issue
#748

**Comment by NathanFallet** [comment] 2021-08-24 13:17
Duplicate of #748

**Closed** 2021-08-24 13:18 UTC
Labels: duplicate
