### ISSUE TITLE
Difficulty Using SQLite.swift with SQLCipher in new XCode 7 projects - outdated documentation

### ISSUE THREAD

**Issue by quangdog** [stephencelis/SQLite.swift#301] opened 2015-12-14 22:17 UTC
I'm starting a new iOS application, and would very much like to use SQLite.swift for my database interactions.  I need to encrypt the database file on the device, and SQLite.swift appears to offer an excellent API for working with SQLite files as well as compatibility with sqlcipher.  However, I'm unable to get SQLite.swift imported into a test project at all.  

I've tried following the instructions in the readme here: https://github.com/stephencelis/SQLite.swift/blob/master/README.md as well as in the installation documentation here: https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#installation

Attempts to install using cocoapods (either with our without sqlcipher) fail with the following error: 
`[!] Error installing SQLite.swift`
`[!] /usr/local/git/bin/git clone https://github.com/stephencelis/SQLite.swift.git`
`/var/folders/yl/8y8f2tgx1bd2n3yf2fdkbs6m0000gp/T/d20151214-10749-r621bl --single-branch --depth 1 --branch swift-2`
`error: unknown option 'single-branch'`

So I attempted the manual install by cloning the repository then adding the .xcodeproj file to my simple project and following the instructions for adding the framework to my project.  This works for getting plain sqlite support working, but I am unable to get sqlcipher support added.  The instructions say "Make sure the sqlcipher working copy is checked out in Xcode. If sqlcipher.xcodeproj is unavailable (i.e., it appears red), go to the Source Control menu and select Check Out sqlcipher… from the sqlcipher menu item." - but in XCode 7.2 when I try to "Check Out sqlcipher" from that menu item, I get a box that lets me select the branch, and when I select master the box just disappears and the project is not checked out. 

So I manually checked the sqlcipher project out into the Vendor directory in the SQLite.swift project, hook everything up in XCode, and try to compile, but get this error from the compiler: 

No such file or directory: '/Users/kimball/Desktop/XCode7 Tutorials/SQLite.swift/Vendor/sqlcipher/sqlite3.c'

I understand that the sqlite3.c is supposed to be an amalgamation source file, but I can't figure out how to get it created. 

Any help at all would be greatly appreciated.

**Comment by quangdog** [comment] 2015-12-14 22:23
Holy crap... After 3 hours fighting with this, I just figured out the problem: I had my projects stored in a directory called "XCode7 Tutorials", and apparently some of the stuff Xcode does under the hood cannot deal with the spaces in the directory name.  Removed the space, and suddenly I can compile a test project with sqlite.swift and sqlcipher support.

**Comment by Huato115** [comment] 2015-12-15 08:17
I stucked for manual install sqlite.
After I had used POD.It's work . No problem again.
Try ->https://cocoapods.org/ or https://guides.cocoapods.org/using/using-cocoapods.html

**Comment by mikemee** [comment] 2016-01-06 20:54
As this appears to be a duplicate of #202, I'm closing this as part of a general issue cleanup. Please re-open if you have more information or feel this should still be active. Thanks!

**Closed by mikemee** 2016-01-06 20:54 UTC
Labels: duplicate
