### ISSUE TITLE
compiled with xcode7.2 failed

### ISSUE THREAD

**Issue by bytegh** [stephencelis/SQLite.swift#330] opened 2016-01-18 08:26 UTC
Hi guys,

When I try to run  "carthage update --platform iOS", I got this issue:
"xcodebuild: error: Scheme SQLiteCipher Mac is not currently configured for the build action."
I have tried all the branches & tags.
but seems no luck.

can you help me checking this? 

thanks!

**Comment by mikemee** [comment] 2016-01-18 14:27
What's strange about this is the word "Cipher" in there. Afaik there is no cipher in the SQLite.swift build anymore.  Can you post your Cartfile please? That would probably be a good starting point. Thanks!

**Comment by stephencelis** [comment] 2016-01-18 14:29
I think this may be a caching issue based on an old, pre-0.9 release. Either that or the SQLCipher Mac scheme is still somehow in the project file.

**Comment by bytegh** [comment] 2016-01-19 03:55
thanks for reply:
github "spire-inc/Bond" "v4.2.2"
github "Alamofire/Alamofire" ~> 3.0
github "stephencelis/SQLite.swift" ~> 0.9.2
github "Quick/Quick" "5fff1989f54b73f9d51725727e04aafb9557b41e"
github "Quick/Nimble" "c2aafa5da886f4e44ee29b4faaaa20fdac8a9369"
github "SnapKit/SnapKit" >= 0.15.0

this is my cartfile.

**Comment by mikemee** [comment] 2016-01-19 22:30
@bytegh Thanks! 

So, here's where I'm puzzled. On my clean checkout of this repo, if I do:

`grep -rl SQLCipher *`

I get back:

```
Documentation/Planning.md
README.md
```
If I do the same thing for "SQLite", I get pretty much every file, including both the `xscheme` files.  If I go to another directory where I have a simple test project with `Cartfile`:
```
github "stephencelis/SQLite.swift"
```
Then when I run `carthage update` I get:
```
$ carthage update
*** Fetching SQLite.swift
*** Checking out SQLite.swift at "0.9.2"
*** xcodebuild output can be found in /var/folders/fn/m4qv73410870r7xf2fpppwmm0000gn/T/carthage-xcodebuild.hoTErj.log
*** Building scheme "SQLite Mac" in SQLite.xcodeproj
*** Building scheme "SQLite iOS" in SQLite.xcodeproj
```
And if I grep for `SQLCipher` I get:
```
Carthage/Checkouts/SQLite.swift/Documentation/Planning.md
Carthage/Checkouts/SQLite.swift/README.md
```
So I'm wondering what might be different about your set up.  When you run `carthage update` does it say `Checking out SQLite.swift at "0.9.2"`, or something else perhaps?

**Comment by mikemee** [comment] 2016-01-20 00:36
Just realized I was searching for `SQLCipher` above instead of `SQLiteCipher`.  I've just repeated and got essentially the same results (only `Planning.md` mentions `SQLiteCipher`, not readme or docs).

Closing this out for now. Definitely feels like some sort of caching problem and/or Carthage isn't pulling in the latest version like it should (as far as we can tell the string "SQLiteCipher" doesn't appear _anywhere_ in the latest releases).  Perhaps we have a Carthage configuration issue, but we're unable to reproduce it. If anyone has more info, please add it to this issue and re-open. Thanks!

**Closed by mikemee** 2016-01-20 00:36 UTC
