### ISSUE TITLE
How to batch insert?

### ISSUE THREAD

**Issue by longlylong** [stephencelis/SQLite.swift#464] opened 2016-06-29 09:30 UTC
How to batch insert?

**Comment by iNoles** [comment] 2016-06-29 18:25
is this is like transactions?

https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#transactions-and-savepoints

**Comment by longlylong** [comment] 2016-06-30 02:43
thk!!!! like this
try db.transaction {
    for user in usersList{
       try db.run(users.insert(email <- user.email))
    }
}

**Comment by jberkel** [comment] 2016-12-07 17:03
not a bug, closing

**Closed by jberkel** 2016-12-07 17:03 UTC
