### ISSUE TITLE
how can i use Limit query for paging my data in a UITableView

### ISSUE THREAD

**Issue by razan1994alali** [stephencelis/SQLite.swift#511] opened 2016-09-28 09:17 UTC
i have just used this library and i'm able to save and retrieve my local data into a UITableView. but now i want to add paging so that data will load on scrolling. i have just checked the queries that i can use and added to my project the Limit query. But still i'm stuck and don't know how to make the paging process work in my code.
thanks in advance

**Comment by Laptopmini** [comment] 2016-10-17 22:16
The scope of this question is past this library, but you need to fetch your table's data directly from the database.

For the number of rows, just get the COUNT of rows.

For displaying a cell, fetch the record in your table at `.limit(1, offset: index.row)` where `index` is the `NSIndexPath` of the cell.

**Comment by jberkel** [comment] 2016-12-07 16:49
not a bug, closing

**Closed by jberkel** 2016-12-07 16:49 UTC
