### ISSUE TITLE
Multiple JOINS

### ISSUE THREAD

**Issue by ricrio** [stephencelis/SQLite.swift#665] opened 2017-06-08 17:22 UTC
Is it possible to do this select?

```
Select * from compra
left outer join local_loja on (compra.id_local_loja_fk = local_loja.id_local_loja)
left outer join local on (local_loja.id_local_fk = local._id)
left outer join loja on (local_loja.id_loja_fk = loja._id)
Order by local.local_nome
```

I've tried this way:

```
let Tabela_Compra = try db?.prepare(
               " Select * from compra 
left outer join local_loja on (compra.id_local_loja_fk = local_loja.id_local_loja) 
left outer join local on (local_loja.id_local_fk = local.id_local)
 left outer join loja on (local_loja.id_loja_fk = loja.id_loja) 
Order by local.local_nome")
```
I've tried this way too:

```
let Tabela_LL      = Table("local_loja");
let id_ll          = Expression<Int>("id_local_loja");
let id_local_fk    = Expression<Int>("id_local_fk");
let id_loja_fk     = Expression<Int>("id_loja_fk");
        
let Tabela_Local   = Table("local");
let id_local       = Expression<Int>("id_local");
let local_nome     = Expression<String>("local_nome");
        
let Tabela_Loja    = Table("loja");
let id_loja        = Expression<Int>("id_loja");
let loja_nome      = Expression<String>("loja_nome");

let Tabela_Compra = self.tbl_compra.join(.leftOuter, Tabela_LL, on: Tabela_LL[id_ll] == self.tbl_compra[id_local_loja_fk])
                                   .join(.leftOuter, Tabela_Local, on: Tabela_Local[id_local] == Tabela_LL[id_local_fk])
                                   .order(Tabela_Local[local_nome].desc)
```

I've tried this way too:

```
let LL = Table("local_loja").join(.leftOuter, Tabela_Local, on: Tabela_LL[id_local_fk] == Tabela_Local[id_local]);
        
let LLoja = Table("loja").join(.leftOuter, LL, on: LL[id_loja_fk] == Tabela_Loja[id_loja])
      
let Tabela_Compra = Table("compra").join(.leftOuter, LLoja, on: LLoja[id_ll] == self.tbl_compra[id_local_loja_fk]).order(LLoja[loja_nome])

for reg in try db!.prepare(Tabela_Compra)
```

Thank you folks in advance for attention. :)

**Comment by ricrio** [comment] 2017-07-21 14:00
Good morning colleague..
Unfortunately I have not been able to do this type of join yet.
best regards

**Comment by jberkel** [comment] 2021-08-24 18:04
duplicate of #689

**Closed by jberkel** 2021-08-24 18:04 UTC
