### ISSUE TITLE
How can I update multiple columns in a row

### ISSUE THREAD

**Issue by leminhtuan2015** [stephencelis/SQLite.swift#513] opened 2016-10-04 13:52 UTC
let alice = users.filter(id == 1)
do {
    if try db.run(alice.update(email <- "alice@me.com")) > 0 {
        print("updated alice")
    } else {
        print("alice not found")
    }
} catch {
    print("update failed: (error)")
}

How should I do in order to update many field in a record

Example: I would like to update (email, name, age) of an user with id = 1, But I just found we only can update one field at once

Please Help. Thank you guys so much.

**Comment by Laptopmini** [comment] 2016-10-17 22:10
You create an array of Setters:
`var values = [Setter]()`

Then you append your Setters as needed and finally execute `.update(values)`.

**Comment by anthonyjosephfarina** [comment] 2016-10-19 02:33
You can separate each column setter with a comma.

For example:
```swift
let alice = users.filter(id == 1)

try db.run(alice.update(
        email <- "alice@me.com",
        name <- "Alice",
        age <- 24))
```

**Comment by jberkel** [comment] 2016-12-07 16:13
Not a bug, closing.

**Closed by jberkel** 2016-12-07 16:13 UTC

**Comment by robert-cronin** [comment] 2018-04-26 00:02
@anthonyjosephfarina This throws an "Extra call in argument" error for me, this resolved the error:
```
let alice = users.filter(id == 1)

try db.run(alice.update(
        [email <- "alice@me.com",
        name <- "Alice",
        age <- 24]))
```

**Comment by honghaoli** [comment] 2018-11-06 01:06
@robert-cronin 
Thanks for the information!
the ```[]``` is SUPER important and saved my day!
I did not notice the difference at first.
