### ISSUE TITLE
App Crash when build in appstore

### ISSUE THREAD

**Issue by TechGuyVN** [stephencelis/SQLite.swift#175] opened 2015-08-14 14:25 UTC
Hi,

I have upload my app to store, app work ok, but when retrieve data from DB, it crash.
Log crash like picture below , seem crash because retrieve a Int64 in function here:

func initRowData(arr:Row){
        
        let id = Expression<Int>("id")
        
        let code = Expression<String?>("code")
        let name = Expression<String?>("name")
        let nameUnsigned = Expression<String?>("nameUnsigned")
        let firstword = Expression<String?>("firstword")
        //---------
        self.id = arr[id]
        self.code = arr[code]
        self.name = arr[name]
        self.nameUnsigned = arr[nameUnsigned]
        self.firstword = arr[firstword]
        
    }

![screen shot 2015-08-14 at 9 15 18 pm](https://cloud.githubusercontent.com/assets/503529/9275906/a789a8fa-42ca-11e5-89ec-65a7f18146be.png)

Please help me solve this case.

**Comment by stephencelis** [comment] 2015-08-14 14:28
Looks like the underlying value for `id` is `nil`. What's your table creation look like? `Expression<Int>` should only be there for `NOT NULL` columns.

**Comment by TechGuyVN** [comment] 2015-08-14 14:35
Thanks for support , here my create function:
    func createPlaceTable(){
        let path = NSSearchPathForDirectoriesInDomains(
            .DocumentDirectory, .UserDomainMask, true
            ).first as String
        
        let db = Database("\(path)/\(DB_NAME)")
        println(db)
        let place = db[TB_PLACE]
        //db.drop(table:product , ifExists: true)
        
        let id = Expression<Int64>("id")
        
        let code = Expression<String?>("code")
        let name = Expression<String?>("name")
        let nameUnsigned = Expression<String?>("nameUnsigned")
        let firstword = Expression<String?>("firstword")

        db.create(table: place,ifNotExists: true){ t in
            t.column(id, primaryKey: true)
            t.column(code)
            t.column(name)
            t.column(nameUnsigned)
            t.column(firstword)
            
        }
        db.create(index: place, on: code, ifNotExists: true)
        db.create(index: place, on: name, ifNotExists: true)
        db.create(index: place, on: nameUnsigned, ifNotExists: true)
 
    }

here my Model class process data:

//
//  ShippingAdressDTO.swift
//  EcommerceApp
//
//  Created by Hoang Quoc Viet on 3/26/15.
//  Copyright (c) 2015 vihat. All rights reserved.
//

import Foundation
//
//  ProductDTO.swift
//  CommercersMagento
//
//  Created by Hoang Quoc Viet on 1/6/15.
//  Copyright (c) 2015 Hoang Quoc Viet. All rights reserved.
//

import Foundation
import UIKit







class PlaceDTO: NSObject {
    
    var id:Int64 = 0
    var code:String!
    var name:String!
    var nameUnsigned:String!
    var firstword:String! = ""
    
    
    
    
    
    override init() {
        super.init()
        
    }
    
    func initData(str:AnyObject?){
        var json =  JSON(str!)
        initDataJson(json)
    }
    
    func initDataJson(json:JSON){
        
        //Do something you want
        
        self.code = json["code"].string
        self.name = json["name"].string
        self.nameUnsigned = json["nameUnsigned"].string
        let str = split(nameUnsigned as String, { $0 == " " })
        for string in str {
            self.firstword = self.firstword + string[0]
        }

    }
    
    func initRowData(arr:Row){
        
        let id = Expression<Int64>("id")
        
        let code = Expression<String?>("code")
        let name = Expression<String?>("name")
        let nameUnsigned = Expression<String?>("nameUnsigned")
        let firstword = Expression<String?>("firstword")

        
        
        //---------
        self.id = arr[id]
        self.code = arr[code]
        self.name = arr[name]
        self.nameUnsigned = arr[nameUnsigned]
        self.firstword = arr[firstword]
        
    }
    
    func getPlaceByCode(co:String!){
        let path = NSSearchPathForDirectoriesInDomains(
            .DocumentDirectory, .UserDomainMask, true
            ).first as String
        
        let db = Database("\(path)/\(DBManager.sharedInstance.DB_NAME)")
        println(db)
        let place = db[DBManager.sharedInstance.TB_PLACE]
        
        let code = Expression<String?>("code")
      
        for p in place.filter(code == co){
            self.initRowData(p)
        }
        // inserted id: 1
        //alice = users.filter(id == insertedID)
        
        
    }
    
    func saveToDB(){
        let path = NSSearchPathForDirectoriesInDomains(
            .DocumentDirectory, .UserDomainMask, true
            ).first as String
        
        let db = Database("\(path)/\(DBManager.sharedInstance.DB_NAME)")
        println(db)
        let place = db[DBManager.sharedInstance.TB_PLACE]
        
        let code = Expression<String?>("code")
        let name = Expression<String?>("name")
        let nameUnsigned = Expression<String?>("nameUnsigned")
        let firstword = Expression<String?>("firstword")

        var values = [Setter]()
        values.append(code <- self.code)
        values.append(name <- self.name)
        values.append(nameUnsigned <- self.nameUnsigned)
        values.append(firstword <- self.firstword)
        
        let (id, statement) = place.insert(values)
        if let id = id {
            println("inserted id: \(id)")
            self.id = id
        } else if statement.failed {
            println("insertion failed: \(statement.reason)")
        }
        // inserted id: 1
        //alice = users.filter(id == insertedID)
        
        
    }
    
}

**Comment by TechGuyVN** [comment] 2015-08-14 14:55
I have view DB on my Iphone, it dont have any column null for place Table.
it's look kike this:
![screen shot 2015-08-14 at 9 53 17 pm](https://cloud.githubusercontent.com/assets/503529/9276566/fe9d60e2-42ce-11e5-8573-5ac517bbeaaf.png)

**Comment by TechGuyVN** [comment] 2015-08-14 15:13
one more try: i have modify: 
        let id = Expression<Int64>("id")
with
        let id = Expression<Int64?>("id")

app work fine, but nothing load from DB, although have data in table Place?.
I run error in Iphone6 and iphone 5s, but when run in iphone 5 with same version error does happend.

Please help me solve this,

**Comment by stephencelis** [comment] 2015-08-14 16:17
Hm, could you zip the project up and email it to me (see my profile)? I'll see if I can reproduce it on my 5s.

**Comment by TechGuyVN** [comment] 2015-08-15 09:36
i Have send source code for you, and step to step to reproduce the bug.
Please take a look :).
Thanks you!.

**Comment by TechGuyVN** [comment] 2015-08-17 02:49
Hi Stephencelis,

Did you receive my email?. i just want make sure for this.

**Comment by stephencelis** [comment] 2015-08-17 03:33
Yup! I'm just traveling this week and haven't had a chance to check it out yet.

**Comment by TechGuyVN** [comment] 2015-08-17 03:35
Okay, wish you have a good time :+1:

**Comment by mikemee** [comment] 2016-01-08 18:31
@TechGuyVN - did this ever resolve itself, or did you find a solution?

_Going through old issues to try and either fix them or close them...)

**Comment by mikemee** [comment] 2016-01-11 04:34
Closing this out. Please re-open if this is still a problem. Thanks!

**Closed by mikemee** 2016-01-11 04:34 UTC

**Comment by TechGuyVN** [comment] 2016-01-12 04:20
i sent @stephencelis  my source but have no response, so i have to move to another DBA for sqlite :(.

**Comment by mikemee** [comment] 2016-01-12 04:34
I guess he got busy. The joys and realities of open source. I'm happy to take a look at it if you still have it around. I'm digging into the library a bit as I want to use it some of my apps, so fixing some of these bugs is currently a high priority for me (and @stephencelis is being very supportive).

**Comment by iNoles** [comment] 2016-01-12 05:34
It should be t.column(id, primaryKey: .Autoincrement) so id will be automatically added.
