### ISSUE TITLE
TALLY.select(*).filter(DATE >= startDate)报错

### ISSUE THREAD

**Issue by fortitude1990** [stephencelis/SQLite.swift#890] opened 2019-03-26 07:42 UTC
xcode10.2， filter内使用>=判断符，会导致      
``` 
 try connection.check(sqlite3_prepare_v2(connection.handle, SQL, -1, &handle, nil))

```
返回报错信息
near ":_": syntax error

**Comment by tanzolone** [comment] 2019-03-26 14:14
Duplicate of #888

**Comment by lanephillips** [comment] 2019-04-03 21:07
#888 is closed, but I've pod updated, and I'm still getting this error, too.

My failing line of code:

`try db.run(table.filter(timestamp < before).delete())`

(where "db" is a Connection, "table" is a Table, "timestamp" is a Expression\<Date>, and "before" is a Date)

This generates the statement `DELETE FROM "some_table" WHERE ("timestamp" <(_:_:) ?)`.

Apparently the Date gets encoded as `(_:_:) ?`

**Comment by lanephillips** [comment] 2019-04-05 14:15
It turns out the podspec version has not been updated, so Cocoapods is downloading a stale version of the repo. I worked around this by linking my Podfile directly to the repo.

**Comment by Yigang0622** [comment] 2019-04-19 20:00
You use like:
`let query = table.filter(0...10 ~= value)`
to filter out value between 0 and 10

**Comment by NathanFallet** [comment] 2021-08-24 08:42
Should be fixed by 0.13.0. If not, please reopen.

**Closed** 2021-08-24 08:43 UTC
Labels: bug
