### ISSUE TITLE
Can't use with Xcode 7 beta2

### ISSUE THREAD

**Issue by zhouzizi** [stephencelis/SQLite.swift#147] opened 2015-06-27 07:40 UTC
Module file was created by an older version of compiler.How can i do?

**Comment by zhouzizi** [comment] 2015-06-27 08:19
And I use xcode convert tolastswiftsynctax ,but it also havs many bug

**Comment by stephencelis** [comment] 2015-06-27 16:51
Closing as a dupe of https://github.com/stephencelis/SQLite.swift/issues/133.

**Closed by stephencelis** 2015-06-27 16:51 UTC
