### ISSUE TITLE
Queries not working properly when using Encodable with optional values

### ISSUE THREAD

**Issue by kamzab95** [stephencelis/SQLite.swift#989] opened 2020-02-21 08:01 UTC
##  Build Information
version: 0.12 master
xcode: 11.3 iOS: 13.2
integrated with: Carthage

## Description

For
```
class SomeExpression {
    static let name = Expression<String?>("name")
}

class User: Codable {
    var name: String?
}
```

Query 
```
func foo(name: String)  -> User? { 
    let query = self.table.filter(SomeExpression.name == name)
    ...
}
```
won't work properly if data were inserted to the database as Encodable. In this case **name will never be found**.
Name, which is String? will be put to database as "\\"aabbbbcccc\\"". The issue is caused by this additional quotes.

The workaround for this issue is adding the quotes while creating the query :
```
func foo(name: String)  -> User? { 
    let query = self.table.filter(SomeExpression.name == "\"\(name)\"") // workaround
    ...
}
```

**Comment by TenMaKo** [comment] 2020-03-20 14:47
```
func encode<T>(_ value: T, forKey key: Key) throws where T: Swift.Encodable {
    if let data = value as? Data {
        self.encoder.setters.append(Expression(key.stringValue) <- data)
    } else if let string = value as? String {
        self.encoder.setters.append(Expression(key.stringValue) <- string)
    } else {
        let encoded = try JSONEncoder().encode(value)
        let string = String(data: encoded, encoding: .utf8)
        self.encoder.setters.append(Expression(key.stringValue) <- string)
    }
}
```

Make the above modification in Coding.swift to fix this issue.

**Comment by rahulvyas** [comment] 2020-04-27 07:26
> ```
> func encode<T>(_ value: T, forKey key: Key) throws where T: Swift.Encodable {
>     if let data = value as? Data {
>         self.encoder.setters.append(Expression(key.stringValue) <- data)
>     } else if let string = value as? String {
>         self.encoder.setters.append(Expression(key.stringValue) <- string)
>     } else {
>         let encoded = try JSONEncoder().encode(value)
>         let string = String(data: encoded, encoding: .utf8)
>         self.encoder.setters.append(Expression(key.stringValue) <- string)
>     }
> }
> ```
> 
> Make the above modification in Coding.swift to fix this issue.

where is this class  Coding.Swift ? can you please provide the class

**Comment by kamzab95** [comment] 2020-04-27 08:42
> where is this class Coding.Swift ? can you please provide the class

I think it's SQLite.swift/Sources/SQLite/Typed/Coding.swift line: 131 (class SQLiteEncoder)

**Comment by rahulvyas** [comment] 2020-04-27 12:59
> > where is this class Coding.Swift ? can you please provide the class
> 
> I think it's SQLite.swift/Sources/SQLite/Typed/Coding.swift line: 131 (class SQLiteEncoder)

So we need to modify library source code ?

**Comment by TenMaKo** [comment] 2020-04-27 14:33
> > where is this class Coding.Swift ? can you please provide the class
> 
> I think it's SQLite.swift/Sources/SQLite/Typed/Coding.swift line: 131 (class SQLiteEncoder)

Yes it is.

> So we need to modify library source code ?

If you want to use it with Codable and optional values, yes you do.

**Comment by NathanFallet** [comment] 2021-08-23 09:54
Duplicate of #997

**Closed** 2021-08-23 09:54 UTC
Labels: bug
