### ISSUE TITLE
No such module 'SQLiteObjc'

### ISSUE THREAD

**Issue by tomasen** [stephencelis/SQLite.swift#990] opened 2020-02-22 03:59 UTC
## Build Information

- SQLite.swift version, 0.12.2
- XCode 11.3.1
- How do do you integrate SQLite.swift in your project?
    - Swift Package manager

After added the swift package dependency, unit tests targets in my project are unable to build and test. It shows build error and compiles error as the following screenshots.

[build error](https://pasteboard.co/IVNTeQi.png)
[compile error](https://pasteboard.co/IVNUBFO.png)

**Comment by CodeMan8** [comment] 2020-07-02 07:11
have you find and solution ?

**Comment by teodorpenkov** [comment] 2020-07-07 14:45
Have you find any solution?

**Comment by CodeMan8** [comment] 2020-07-07 15:31
yeah I have found solution the problem is about sqlite library first remove
all derived data from xcode then delete all pod files in your project and
.xcworkspace file

After that last thing you have to do init pod file and install again sqlite
library
it will be update sqlite library files smoothly


7 Tem 2020 Sal 17:45 tarihinde Teodor Penkov <notifications@github.com>
şunu yazdı:

**Comment by teodorpenkov** [comment] 2020-07-15 15:08
I experience similar issue with Carthage, sometimes it's building successfully and sometimes it's not, still struggling to figure out why, but it sounds similar to your issue, unfortunately the workaround it's not working for me

**Comment by izaguirrejoe** [comment] 2021-02-27 05:13
Any word on this error? Can't run tests....

**Comment by NathanFallet** [comment] 2021-08-22 16:39
Should be fixed with the `0.13.0`

**Closed by NathanFallet** 2021-08-22 16:39 UTC
