### ISSUE TITLE
How to write a "if exists" clause before inserting & updating

### ISSUE THREAD

**Issue by FateRiddle** [stephencelis/SQLite.swift#405] opened 2016-04-13 11:24 UTC
I'm building a login view for my app. Need to check if userID is in SQLite tb_user table everytime I login. If there exists a matching userID, then proceed to update field isUserLoggedIn to true; else insert userID, userName, password, and true for isUserLoggedIn.

just wondering how to write `if exists( select 1 from tb_user where userID = @in_userID ) update tb_user set isUserLoggedIn = true where userID = @in_userID` in SQLite.swift?

**Comment by jberkel** [comment] 2016-12-07 16:49
not a bug, closing

**Closed by jberkel** 2016-12-07 16:49 UTC

**Comment by FalconBFR** [comment] 2020-07-24 03:29
Hey @jberkel  that is not very helpful. Same problem here 4 years later
