### ISSUE TITLE
 Cannot find an overload with whole module optimization on

### ISSUE THREAD

**Issue by krzyzanowskim** [stephencelis/SQLite.swift#113] opened 2015-04-21 09:25 UTC
There seems to be the issue with Swift 1.2 and `SWIFT_WHOLE_MODULE_OPTIMIZATION = YES`
It only happening with this option on. It seems to be Swift issue rather than SQLite, however since it is not working as expected maybe there is a way to workaround this.

```swift
//ERROR: Cannot find an overload for 'contains' that accepts an argument list of type '([String], Expression<String>)'
let val = contains(["A","B","C"], Expression<String>("word"))
```

**Comment by stephencelis** [comment] 2015-04-21 12:15
The above fails when _your_ target has **Whole Module Optimization** enabled, or when the SQLite target does? I just tested it in a fresh project and it compiles.

I thought this may be related to https://github.com/stephencelis/SQLite.swift/issues/95, but that one persists even with **Whole Module Optimization** disabled (on the SQLite target).

**Comment by krzyzanowskim** [comment] 2015-04-21 12:17
it fails when my project has it enabled, and disappear when disabled.
SQLite.swift has enabled this optimization all the time in my case.

**Comment by stephencelis** [comment] 2015-04-21 12:19
Gotcha, sounds like a Swift bug. Not sure what I can do here. Have you filed a rdar?

**Comment by stephencelis** [comment] 2015-04-22 16:40
Closing since it's out of my control. Sounds like the solution above helped, but please reference a bug report here if you submit one!

**Closed by stephencelis** 2015-04-22 16:40 UTC
Labels: swift bug

**Comment by jckarter** [comment] 2015-07-20 17:54
We were looking into this as rdar://problem/20635760. We haven't been able to reproduce the problem in Xcode 7. Have you still run into issues?

**Comment by stephencelis** [comment] 2015-07-20 18:24
@jckarter I believe this is fixed but I haven't had time to complete the migration to 2.0 yet and completely verify. Thanks for looking into this!
