### ISSUE TITLE
How to catch interrupted error?

### ISSUE THREAD

**Issue by brookhong** [stephencelis/SQLite.swift#1117] opened 2022-03-13 03:15 UTC
Querying in some table is time-consuming, I want to intentionally interrupt previous query with `db.interrupt()`, which works fine.

But got below error from previous query, how can I catch the error without crashing the application?

    SQLite/Statement.swift:211: Fatal error: 'try!' expression unexpectedly raised an error: interrupted (code: 9)

Tried below code, but to no avail.

        do {
            let sequences = try db.prepare(repos.select(key))
            rows = Array(sequences.enumerated())
        } catch {
            print(error)
        }

**Comment by SaladDays831** [comment] 2022-04-11 17:09
Also happening to me when I call db.interrupt()
Crashes in Statement.swift, on

```
extension FailableIterator {
    public func next() -> Element? {
        // swiftlint:disable:next force_try
        try! failableNext()
    }
}
```

**Comment by NathanFallet** [comment] 2022-04-19 13:32
Closing as it is a duplicate of #1118. We're going to keep only one issue opened to track this problem.

**Closed by NathanFallet** 2022-04-19 13:32 UTC
