### ISSUE TITLE
Unable to create database

### ISSUE THREAD

**Issue by adnanafzal565** [stephencelis/SQLite.swift#1032] opened 2020-11-20 03:02 UTC
I am getting the following error from the master branch while creating a connection to the database:

`cannot open file at line
open(//my_db.sqlite3)
The operation couldn’t be completed. (SQLite.Result error 0.)`

I wanted to ask, do I have to give some permissions to create a database?

If yes, kindly let me know which ones and how to add them.

Thanks.

**Comment by NathanFallet** [comment] 2021-08-22 15:20
@adnanafzal565 Can you show us your code please?

**Comment by NathanFallet** [comment] 2021-08-23 10:10
Duplicate of #982

**Closed** 2021-08-23 10:10 UTC
Labels: question, information needed
