### ISSUE TITLE
perform distinct oepration sqlite.swift branches - swift 2 

### ISSUE THREAD

**Issue by irshad9998** [stephencelis/SQLite.swift#231] opened 2015-09-24 07:14 UTC
Perform distinct query app crash no such column name

table contains 3 columns but i want to use only one 

       for user in db.prepare(users.select(distinct:main).filter(main != "Bookmarks"))
        {
            print("id: \(user[main]))")
            
            data = Array(arrayLiteral: user)
        }

help me how to solved it

**Comment by stephencelis** [comment] 2015-10-01 10:32
Would you please provide more information? Sounds like the "users" table doesn't have the column "name"?

**Comment by mikemee** [comment] 2016-01-10 01:35
I can't reproduce this. Here is a little playground example that tries to mimic your scenario and it runs with the current release with no errors as follows:
```swift
import SQLite

let db = try! Connection()
db.trace { print($0) }

let emails = Table("emails")
let to = Expression<String>("to")
let subject = Expression<String?>("subject")

try! db.run(emails.create {t in t.column(to); t.column(subject)} )
try! db.run(emails.insert(to <- "stephen@example.com", subject <- "Hello, world!" ))

for user in try db.prepare(emails.select(distinct:to).filter(to != "me@example.com")) {
    print("id: \(user[to])")
}
```
Output:
```SQL
CREATE TABLE "emails" ("to" TEXT NOT NULL, "subject" TEXT)
INSERT INTO "emails" ("to", "subject") VALUES ('stephen@example.com', 'Hello, world!')
SELECT DISTINCT "to" FROM "emails" WHERE ("to" != 'me@example.com')
id: stephen@example.com
```
Please re-open if you feel this was closed in error and you have more information. Thanks!

**Closed by mikemee** 2016-01-10 01:35 UTC
