### ISSUE TITLE
Broken CocoaPods instructions on the Swift 2 branch

### ISSUE THREAD

**Issue by zixun** [stephencelis/SQLite.swift#196] opened 2015-09-08 14:15 UTC
add SQLite.swift to my swift 2 application as the document in readme : 

```
pod 'SQLite.swift',
git: 'https://github.com/stephencelis/SQLite.swift.git'

# instead, for SQLCipher support
pod 'SQLiteCipher.swift',
git: 'https://github.com/stephencelis/SQLite.swift.git'
```

but CocoaPods print: 

```
[!] Unable to find a specification for 'SQLiteCipher.swift'.
```

why ? how to use  SQLite.swift in swift 2 Application?

**Comment by stephencelis** [comment] 2015-09-08 14:18
The [readme](https://github.com/stephencelis/SQLite.swift/blob/swift-2/README.md) and [documentation](https://github.com/stephencelis/SQLite.swift/blob/swift-2/Documentation/Index.md) on that branch should be up-to-date for the most part.

**Comment by zixun** [comment] 2015-09-08 14:19
@stephencelis  thank you! but the cocoapod print: 

[!] Unable to find a specification for 'SQLiteCipher.swift'.

**Comment by stephencelis** [comment] 2015-09-08 14:24
Ohhh, you know what? You need to be on the `swift-2` branch:

``` rb
pod 'SQLiteCipher.swift',
  git: 'https://github.com/stephencelis/SQLite.swift.git',
  branch: 'swift-2'
```

**Comment by zixun** [comment] 2015-09-08 14:26
@stephencelis  ye~but the readme diid not specify it

**Comment by stephencelis** [comment] 2015-09-08 14:37
@zixun That's true! I'll try to fix that soon. Thanks for the heads-up!

**Comment by lkoskela** [comment] 2015-09-21 07:26
I've got the 'swift-2' branch set in my Podfile but cocoapods still complains about being "unable to find a specification" for SQLite.swift:

    $ pod install
    [...]
    Analyzing dependencies
    Pre-downloading: `SQLite.swift` from `https://github.com/stephencelis/SQLite.swift.git`, branch `swift-2`
    [!] Unable to find a specification for 'SQLite.swift'.
    [!] Unable to load a podspec from `SQLite.swift.podspec`, skipping:
    Pod::DSLError
    [!] Unable to load a podspec from `SQLiteCipher.swift.podspec`, skipping:
    Pod::DSLError

**Comment by blurrah** [comment] 2015-09-21 17:17
@lkoskela Same problem here, master branch works like a charm, but swift-2 branch displays the error.

**Comment by doug-l-mitchell** [comment] 2015-09-24 15:07
Same problem

Analyzing dependencies
Pre-downloading: `SQLite.swift` from `https://github.com/stephencelis/SQLite.swift.git`, branch `swift-2`
[!] Unable to find a specification for 'SQLite.swift'.

[!] Unable to load a podspec from `SQLite.swift.podspec`, skipping:

Pod::DSLError

[!] Unable to load a podspec from `SQLiteCipher.swift.podspec`, skipping:

Pod::DSLError

**Comment by AndyDunn** [comment] 2015-09-24 21:10
Same here. Trying to get this working on Xcode 7.

**Comment by ferranvila** [comment] 2015-09-29 08:51
Any updates? Trying with:
Xcode : 7.0.1 (7A1001)
CocoaPods : 0.38.2

**Comment by AndyDunn** [comment] 2015-09-30 09:40
@stephencelis Is there an easy work around for this until it's resolved?

**Comment by zzpaf** [comment] 2015-09-30 12:03
Sorry if I did not understand something, but it is working fine for me... My Podfile (Just in case it can help somebody:

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '9.0'
    use_frameworks!

    pod 'SQLite.swift',
    git: 'https://github.com/stephencelis/SQLite.swift.git', branch: 'swift-2'

I am using cocoapods-core-0.38.2.gem

**Comment by stephencelis** [comment] 2015-09-30 12:07
I'll be looking into this today. Can those still having problems post:

- OS X version
- Xcode version
- CocoaPod version: `pod --version`
- Ruby version: `ruby -v`

@AndyDunn One workaround would be to use the traditional install method.

**Comment by zzpaf** [comment] 2015-09-30 12:28
So that you have a reference on this configuration it is working with the above Podfile:
OS X: 10.10.5
Xcode: Version 7.0 (7A220)
CocoaPods: 0.38.2
Ruby: 2.0.0p481

**Comment by ferranvila** [comment] 2015-09-30 12:52
My configuration:
OS X: 10.10.5
Xcode: 7.0.1 (7A1001)
Cocoapods: 0.38.2
Ruby: ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]

Podfile:

```
xcodeproj 'adaptive-arp-rt.xcodeproj'
platform :ios, '8.0'
use_frameworks!
pod 'AdaptiveArpApi', '2.2.14'
pod 'CryptoSwift', '0.0.15'
pod 'SQLite.swift', git: 'https://github.com/stephencelis/SQLite.swift.git', branch: 'swift-2'
```
And the error:

```
Analyzing dependencies
Pre-downloading: `SQLite.swift` from `https://github.com/stephencelis/SQLite.swift.git`, branch `swift-2`
[!] Unable to find a specification for 'SQLite.swift'.
[!] Unable to load a podspec from `SQLite.swift.podspec`, skipping:
Pod::DSLError
[!] Unable to load a podspec from `SQLiteCipher.swift.podspec`, skipping:
Pod::DSLError
```

**Comment by AndyDunn** [comment] 2015-09-30 16:22
My configuration which isn't working:

OSX: 10.10.5
Xcode: 7.0 (7A220)
Pod: 0.38.2
Ruby: 2.0.0p247

**Comment by stephencelis** [comment] 2015-10-01 10:42
I haven't been able to reproduce on my El Capitan machine. I'll get my hands on a Yosemite machine later today and see if I have better luck. What does `pod --verbose install` look like for you?

**Comment by blurrah** [comment] 2015-10-01 10:46
Isn't it an idea to merge the swift-2 branch to master and rather keep a swift 1.2 branch? Most projects have already done that the day Swift 2 was released.

**Comment by stephencelis** [comment] 2015-10-01 10:50
@blurrah It's mostly been a time issue for me, unfortunately :disappointed: I've been traveling a lot lately and haven't had the time I need to get everything situated. There are a few changes to the project I'd like to make before merging everything to master.

**Comment by ferranvila** [comment] 2015-10-01 10:53
The ```pod --verbose install``` gives me:

```
...
Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)

Finding Podfile changes
  M SQLite.swift
  - AdaptiveArpApi
  - CryptoSwift

Fetching external sources
-> Pre-downloading: `SQLite.swift` from `https://github.com/stephencelis/SQLite.swift.git`, branch `swift-2`
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/stephencelis/SQLite.swift.git
     /var/folders/st/l41vm26n1n7f20p86nzs2kgm0000gn/T/d20151001-37801-f3jd4o
     --single-branch --depth 1 --branch swift-2
     Cloning into '/var/folders/st/l41vm26n1n7f20p86nzs2kgm0000gn/T/d20151001-37801-f3jd4o'...
[!] Unable to find a specification for 'SQLite.swift'.

/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/lib/cocoapods/external_sources/abstract_external_source.rb:111:in `block in pre_download'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/lib/cocoapods/external_sources/abstract_external_source.rb:106:in `pre_download'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:453:in `fetch_external_source'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:430:in `block (2 levels) in fetch_external_sources'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:429:in `each'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:429:in `block in fetch_external_sources'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:428:in `fetch_external_sources'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:69:in `analyze'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:210:in `analyze'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:133:in `block in resolve_dependencies'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:132:in `resolve_dependencies'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:104:in `install!'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/Users/administrator/.rvm/gems/ruby-2.1.2/bin/pod:23:in `load'
/Users/administrator/.rvm/gems/ruby-2.1.2/bin/pod:23:in `<main>'
/Users/administrator/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/administrator/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

[!] Unable to load a podspec from `SQLite.swift.podspec`, skipping:

Pod::DSLError

[!] Unable to load a podspec from `SQLiteCipher.swift.podspec`, skipping:

Pod::DSLError

```
Thanks!

**Comment by lkoskela** [comment] 2015-10-01 16:07
My configuration is

- ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin12.3.0]
- Cocoapods 0.38.2
- OS X Yosemite 10.10.5 (14F27)
- Xcode 7.0 (7A218)

Podfile looks like this:

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '8.0'
    use_frameworks!
    pod 'SQLite.swift', git: 'https://github.com/stephencelis/SQLite.swift.git', branch: 'swift-2'

And here's the error I'm getting:

    -> Pre-downloading: `SQLite.swift` from `https://github.com/stephencelis/SQLite.swift.git`, branch `swift-2`
     > Git download
     > Git download
         $ /usr/local/bin/git clone https://github.com/stephencelis/SQLite.swift.git /var/folders/28/8n36xp6n4x7990tdt049g5gc0000gn/T/d20151001-15071-1d0p8m9 --single-branch --depth 1 --branch swift-2
         Cloning into '/var/folders/28/8n36xp6n4x7990tdt049g5gc0000gn/T/d20151001-15071-1d0p8m9'...
    [!] Unable to find a specification for 'SQLite.swift'.

**Comment by nickmshelley** [comment] 2015-10-01 16:18
Sorry if this is an ignorant answer, but I thought I'd post it in case it helps someone...

I had problems a few months ago with some of my pods not getting the right version, and it ended up that my specs repo was out of date. Following these instructions fixed the issue for me: http://blog.cocoapods.org/Repairing-Our-Broken-Specs-Repository/

**Comment by mikemee** [comment] 2016-01-06 23:50
Most likely covered by #257 and/or fixed by merging the `swift2` branch into `master`. Please re-open with details if you disagree. Thanks!

**Closed by mikemee** 2016-01-06 23:50 UTC
Labels: question
