### ISSUE TITLE
Egrep: SQLite.Swift is a directory Error

### ISSUE THREAD

**Issue by PranKe01** [stephencelis/SQLite.swift#402] opened 2016-04-08 11:12 UTC
Hi there,
I installed SQLite.Swift using pods. When I build my project, I get 4 Errors:
**Egrep: /Users/YourUserName/YourApp/Pods/Headers/Private/SQLite.Swift: Is a directory**
**Egrep: /Users/YourUserName/YourApp/Pods/SQLite.Swift: Is a directory**
**Egrep: /Users/YourUserName/YourApp/Pods/Target Support Files/SQLite.Swift: Is a directory**
**Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure**

Any ideas how to prevent/fix this errors? They appeared after using SQLite.Swift :|
Thanks in advance :)

**Comment by ryanholden8** [comment] 2016-04-08 13:06
@PranKe01 Are you running SQLite.swift 0.10.1? How did you install SQLite.swift? Cocoapods? Manually? Xcode version? Etc.

**Comment by PranKe01** [comment] 2016-04-08 13:29
I am running XCode 7.3. I installed SQLite.Swift v1.10.1 via cocoapods. It is the only library I am using, which contains a dot in the name...

**Comment by ryanholden8** [comment] 2016-04-08 13:33
What version of cocoapods?

**Comment by PranKe01** [comment] 2016-04-08 14:10
I am using CocoaPods 0.39.0.

**Comment by ryanholden8** [comment] 2016-04-08 14:13
Please read instructions here: https://github.com/stephencelis/SQLite.swift#cocoapods

**Comment by PranKe01** [comment] 2016-04-08 14:23
Ah :) Well this could help. But I think I will wait for the final version 1.0.
Thanks for your help!

**Comment by PranKe01** [comment] 2016-11-05 14:03
Now I am using pod version 1.1.1 and I am still getting this error with SQLite.Swift 0.11.0 :(

**Comment by o15a3d4l11s2** [comment] 2016-11-12 20:14
I am also using CocoaPods 1.1.1 and still getting this error even after `pod deintegrate`.

**Comment by o15a3d4l11s2** [comment] 2016-12-01 09:18
Any update on this one?

**Comment by jberkel** [comment] 2016-12-01 14:27
@o15a3d4l11s2 version of Xcode? can you share your Podfile?

**Comment by o15a3d4l11s2** [comment] 2016-12-04 15:37
@jberkel,  Xcode 8.1 (8B62), Cocoapods 1.1.1

**Comment by jberkel** [comment] 2016-12-05 00:13
@o15a3d4l11s2  does a minimal project with `pod try SQLite.swift` work on your system?

**Comment by o15a3d4l11s2** [comment] 2016-12-05 13:16
I have traced the problem down to a script that I am using to highlight TODO and FIXME tags. It causes the error to show up in the Issue Navigator.

More details regarding the script itself: http://jeffreysambells.com/2013/01/31/generate-xcode-warnings-from-todo-comments

I will try to find a way to modify the script, so it does not emit such errors, but still keep the TODO and FIXME tags showing in the navigator.

I think that you can close the issue, as it is not caused by the pod itself. Thanks for the support.

**Comment by o15a3d4l11s2** [comment] 2016-12-05 13:19
@PranKe01 , do you by any chance use the same script that I mentioned in my precious comment to exact TODO/FIXMEs?

**Closed** 2016-12-05 14:53 UTC

**Comment by PranKe01** [comment] 2016-12-05 15:27
That's right! I also used that script... Thanks for your help :)
