### ISSUE TITLE
Support for CocoaPods

### ISSUE THREAD

**Issue by skrach** [stephencelis/SQLite.swift#44] opened 2015-01-19 12:00 UTC
Now that the current pre release version of CocoaPods [supports](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/) Swift Frameworks I would like to ask if you could provide a podspec for `Sqlite.swift`.

What do you think about this idea?

**Comment by stephencelis** [comment] 2015-01-19 17:59
I'm in favor of this, but am not sure it's possible at the moment. SQLite.swift uses a bridging header to `#include <sqlite3.h>`, which typically isn't allowed in framework targets. I tested a podspec briefly and found that because it generates its own targets, umbrella header, etc., it fails to build.

See: https://github.com/CocoaPods/swift/issues/8.

Meanwhile, it's possible to `import sqlite3` using a custom modulemap file, but this is problematic because the modulemap must have a hard-coded path to the specific linked/includes header, meaning it would have to generate this map dynamically and/or maintain different import paths for `iphoneos`, `iphonesimulator` (perhaps multiple per Xcode build), and `macosx`. CocoaPods would somehow need to have the ability to manage this generation, and SQLite.swift would likely be littered with `#if os(...)` directives.

An alternative would be to link to `libsqlite3.dylib`, but maintain our own, public `#include "sqlite3.h"`, but this seems especially problematic and has a high maintenance cost.

In the end this is a deficiency on Apple's end that will hopefully be resolved with the next major developer release, if only with the inclusion of more core system modulemaps.

Here's the spec I tried if others are interested in trying to tackle this:

``` ruby
Pod::Spec.new do |s|
  s.name = 'SQLite.swift'
  s.module_name = 'SQLite'
  s.version = '0.1.0'
  s.summary = 'A type-safe, Swift-language layer over SQLite3.'

  s.description = <<-DESC
    SQLite.swift provides compile-time confidence in SQL statement syntax and
    intent.
  DESC

  s.homepage = 'https://github.com/stephencelis/SQLite.swift'
  s.license = { type: 'MIT', file: 'LICENSE.txt' }

  s.author = { 'Stephen Celis' => 'stephen@stephencelis.com' }
  s.social_media_url = 'https://twitter.com/stephencelis'

  s.library = 'sqlite3'

  s.source = {
    git: 'https://github.com/stephencelis/SQLite.swift.git',
    tag: s.version
  }

  s.source_files = 'SQLite Common/**/*.{swift,c,h,m}'

  s.xcconfig = {
    'SWIFT_OBJC_BRIDGING_HEADER' => 'SQLite-Bridging-Header.h'
  }
end
```

**Comment by skrach** [comment] 2015-01-20 09:10
Thank you very much for your quick and detailed response! It wasn't clear to me that integrating Sqlite.swift in CocoaPods is non-trivial!

**Comment by robconrad** [comment] 2015-04-12 18:00
+1 for CocoaPods support!

**Comment by stephencelis** [comment] 2015-04-12 18:03
@robconrad Unfortunately not possible right now, but feel free to file a duplicate radar at https://bugreport.apple.com asking for Apple to include a module map for sqlite3!

**Comment by stephencelis** [comment] 2015-05-17 23:31
Alright, 0.37 let's us make this happen! https://github.com/stephencelis/SQLite.swift/commit/0dfbdde2d2fc9181bbfe7e9ebed4adbdf0ff4d63

**Closed by stephencelis** 2015-05-17 23:31 UTC
Labels: enhancement, help wanted

**Comment by k7** [comment] 2015-05-19 08:56
sorry, but I found this:

![bugreport](https://cloud.githubusercontent.com/assets/1393849/7699052/de59c756-fe47-11e4-9d20-33e2b2a00c4b.png)

**Comment by stephencelis** [comment] 2015-05-19 11:14
@k7 Could you please read the [contributing guidelines](https://github.com/stephencelis/SQLite.swift/blob/master/CONTRIBUTING.md#contributing) and follow the instructions there? _E.g._ run a clean build, provide a lot more information, and, if possible, provide a reproducible project? I've installed via CocoaPods using the latest versions of Xcode several times in brand new projects and haven't encountered the issue you're seeing above.

**Comment by k7** [comment] 2015-05-25 07:09
I am sorry not replying earlier. 
Just delete the Xcode Derived Data will fix my problem.

**Comment by steffimueller** [comment] 2015-06-03 00:16
@stephencelis Did what you wrote and included the bridging header with: ``SWIFT_OBJC_BRIDGING_HEADER`` in the podspec file.  I used in the pods bridging header: 
```
#import <TestLib/SomeViewController.h>
```
After installing the pod the bridging header was not installed correctly the files from the pod where not found.

Here is a stackoverflow question on this:  http://stackoverflow.com/questions/30608575/include-pods-bridging-header-to-build-settings

**Comment by stephencelis** [comment] 2015-06-03 00:33
@steffimueller That's an _ooold_ comment. Check out the current pod spec in the repo proper: https://github.com/stephencelis/SQLite.swift/blob/743530d1e56c86b5cd4df5153839a98ecb05bf5f/SQLite.swift.podspec

**Comment by steffimueller** [comment] 2015-06-03 00:53
This does not answer my question. Or could you please point to the correct position?

**Comment by stephencelis** [comment] 2015-06-03 00:55
@steffimueller Not sure what you're asking. I linked directly to a working podspec. I also answered your StackOverflow question.

**Comment by steffimueller** [comment] 2015-06-03 00:57
Well, thank you. The Stackoverflow question is not about pod Swift frameworks. It is just about pure Objective pods. Could you please update your answer on that. Thank you so much.

**Comment by stephencelis** [comment] 2015-06-03 00:58
@steffimueller That's confusing. Bridging headers are for bridging code into Swift. They do not make any sense for pure Objective-C pods.

**Comment by steffimueller** [comment] 2015-06-03 00:59
My pod is pure Objective-C but the project the pod ist installed in is Swift.

**Comment by steffimueller** [comment] 2015-06-03 00:59
What I want to say is that there is just no Swift code in the Pod.

**Comment by stephencelis** [comment] 2015-06-03 01:00
@steffimueller Then why would you need a bridging header in your pod? Projects that use your pod just need to import your pod's headers in the _project's_ bridging header.

**Comment by steffimueller** [comment] 2015-06-03 01:01
I want to skip the projects bridging header and ship the pod with a pre configured bridging header.

**Comment by stephencelis** [comment] 2015-06-03 01:03
@steffimueller You can't and shouldn't. End-developers, at the moment, are expected to manage their own bridging headers. As a pod maintainer you do not (and should not) have the ability to modify their bridging header or project settings.

**Comment by steffimueller** [comment] 2015-06-03 01:04
That is why I want to create a separate bridging header in my pod.

**Comment by stephencelis** [comment] 2015-06-03 01:05
@steffimueller I'm trying to explain that doing so (even if it _were_ possible) would not give you the ability  to do what you want.

**Comment by steffimueller** [comment] 2015-06-03 01:06
Okay so it is impossible?

**Comment by stephencelis** [comment] 2015-06-03 01:08
@steffimueller Nope. Clarified in previous comment.

**Comment by steffimueller** [comment] 2015-06-03 01:08
Thanks for help.
